// Types — public API
export * from "./types/index.js"

// Implementations
export { DefaultAdapterRegistry } from "./tree/AdapterRegistry.js"
export { TreeBuilder } from "./tree/TreeBuilder.js"
export type { TreeBuilderOptions } from "./tree/TreeBuilder.js"
export { TreeTraversal } from "./tree/TreeTraversal.js"
export type { TraversalOptions, TraversalResult } from "./tree/TreeTraversal.js"
export { Retriever } from "./retrieval/Retriever.js"
export type { RetrieverOptions } from "./retrieval/Retriever.js"
export { DependencyExpander } from "./retrieval/DependencyExpander.js"
export { ContextBuilder } from "./retrieval/ContextBuilder.js"
export { ParallelSymbolExtractor } from "./retrieval/ParallelSymbolExtractor.js"
export { SymbolDependencyGraph } from "./retrieval/SymbolDependencyGraph.js"
export { SummaryGenerator } from "./llm/SummaryGenerator.js"
export { TraversalReasoner } from "./llm/TraversalReasoner.js"
export { TraversalCache, TraversalCacheManager } from "./retrieval/TraversalCache.js"
export { FileSystemIndexStore } from "./storage/FileSystemIndexStore.js"
export { FileScanner } from "./storage/FileScanner.js"
export { FileWatcher, FileWatcherManager } from "./storage/FileWatcher.js"
export type { ScanResult, FileScannerOptions } from "./storage/FileScanner.js"
export type { FileChange, FileWatcherEvents } from "./storage/FileWatcher.js"
export { IndexManager } from "./storage/IndexManager.js"
export type { IndexManagerOptions, BuildResult, UpdateResult, StatusResult, WatchOptions } from "./storage/IndexManager.js"
